<a href="https://colab.research.google.com/github/ASingh-AGH/AI_Collab/blob/main/DLMIA%20Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.core.fromnumeric import trace
import numpy as np
import torch as tc
import time

y_size, x_size = 1024, 1024
array = np.zeros((y_size, x_size))
print(f"Dtype: {array.dtype}")
print(f"Shape: {array.shape}")

tensor = tc.zeros((y_size, x_size))
print(f"Dtype: {tensor.dtype}")
print(f"Shape: {tensor.shape}")

Dtype: float64
Shape: (1024, 1024)
Dtype: torch.float32
Shape: torch.Size([1024, 1024])


In [ ]:
!nvidia-smi

Mon Mar 13 19:07:47 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    29W /  70W |    761MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
y_size, x_size = 2048, 2048
array1 = np.random.normal(size=(y_size, x_size))
array2 = np.random.normal(size=(y_size, x_size))

b_t = time.time()
result = array1 + array2
e_t = time.time()
print(f"Elapsed time: {e_t - b_t}")

Elapsed time: 0.012767553329467773


In [ ]:
y_size, x_size = 2048, 2048
array1 = np.random.normal(size=(y_size, x_size))
array2 = np.random.normal(size=(y_size, x_size))
tensor1 = tc.from_numpy(array1)
tensor2 = tc.from_numpy(array2)

b_t = time.time()
tensor1 = tensor1.to("cuda:0")
tensor2 = tensor2.to("cuda:0")
e_t = time.time()
print(f"Elapsed time: {e_t - b_t}")

print(tensor1.device)

b_t = time.time()
result = tensor1 + tensor2
e_t = time.time()
print(f"Elapsed time: {e_t - b_t}")

Elapsed time: 0.014773845672607422
cuda:0
Elapsed time: 0.0004038810729980469


In [ ]:
print(0.012767553329467773 / 0.0008347034454345703)

15.295915452727792


In [ ]:
from torch import nn

class OurNetwork(nn.Module):
  def __init__(self):
    super(OurNetwork, self).__init__()
    self.layer_1 = nn.Linear(1, 1)

  def forward(self, x):
    return self.layer_1(x)

model = OurNetwork()
"""
[N, F]
"""
input_to_model = tc.zeros((4, 1))

output_from_model = model(input_to_model)
print(input_to_model.shape)
print(output_from_model.shape)
print(input_to_model)
print(output_from_model)


torch.Size([4, 1])
torch.Size([4, 1])
tensor([[0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.7413],
        [0.7413],
        [0.7413],
        [0.7413]], grad_fn=<AddmmBackward0>)


In [ ]:
from torch import nn

class OurNetwork2(nn.Module):
  def __init__(self):
    super(OurNetwork2, self).__init__()
    self.layer_1 = nn.Conv2d(3, 16, kernel_size=3, padding=1, bias=False)
    self.act_1 = nn.ReLU()
    self.layer_2 = nn.Conv2d(16, 32, kernel_size=3, padding=1, bias=False)
    self.act_2 = nn.ReLU()

  def forward(self, x):
    x = self.act_1(self.layer_1(x))
    x = self.act_2(self.layer_2(x))
    return x

"""
R^2 (Y, X) -> Value (for RGB -> [R, G, B])
3 x Y x X
"""

model = OurNetwork2()
"""
[N, C, Y, X]
"""
batch_size = 4
no_channels = 3
y_size = 256
x_size = 256
input_to_model = tc.zeros((batch_size, no_channels, y_size, x_size))

output_from_model = model(input_to_model)
print(input_to_model.shape)
print(output_from_model.shape)
# print(input_to_model)
print(output_from_model)


torch.Size([4, 3, 256, 256])
torch.Size([4, 32, 256, 256])
tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]],

         ...,

         [[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0.