<a href="https://colab.research.google.com/github/ASingh-AGH/AI_Collab/blob/main/IAI%20Supervised%20Learning%20exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Artificial Intelligence**

## Supervised Learning

## Beginning

### Part 1: Review questions
Try to answer the following questions.

**Put the answers to these questions in your report. Be concise.** \\
**You won't get any potins for this but answering these questions in obligatory.**

If any of these issues is unclear, please make an effort to recall and review them.

You can always check [these tutorials](https://www.kdnuggets.com/2020/03/24-best-free-books-understand-machine-learning.html) or consult with the teacher.

1. What are the differences between supervised, unsupervised, and reinforcement learning?
2. How is regression different from classification?
3. What are linear regression, decision tree, and neural network?
4. What is the test set, and what is the training set?
5. What is *overfitting*, and what is *underfitting*?
6. How to deal with *overfitting* for linear regression, decision trees, and neural networks?
7. What is Exploratory Data Analysis (EDA), and why do we do it?
8. What is an *outlier*?
9. What metrics can be used to measure the model's performance in supervised learning, and what is their interpretation?
10. What is cross-validation?


### Part 2: Jupyter Notebook

Jupyter Notebook allows you to create documents containing code, graphs, equations, text, etc.

The whole philosophy is based on writing in cells that we can freely and independently edit and run. 

Additionaly, the cells can be interactive.

Jupyter Notebooks allow you to run code written in **Python**, Julia, R, etc.

We use them very often in the case of data analysis, statistical modeling, visualization, Artificial Intelligence.

You can learn more [here](https://jupyter.org/) and [here](https://www.anaconda.com/).

---
Below you can see some examples with basic code.

In [ ]:
print("Hello!") # if you clink on specific cell and press Ctrl+Enter the code is running (alternatively, you can just use 'Play' button on the left of cell)

Hello!


In [ ]:
first_var = 3
first_var

3

In [ ]:
my_list = [x for x in range(10)]
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
my_list += [3, 2, 1]

In [ ]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 2, 1]

---

The cell below is for you -- try writing a simple Python program.

Example task: write a program that returns an NxN array filled with successive numbers of the Fibonacci sequence (recursion) in a spiral.

You can use as many cells as you need. Make your code as readable as possible.

---


In [ ]:
def Fibonacci(n):
    if n < 0: print("Incorrect input")
    elif n == 0: return 0
    elif n == 1 or n == 2: return 1
    else: return Fibonacci(n-1) + Fibonacci(n-2)
i= 12 #i being the nth place in fib
fibarr=[] # initializing an array

for j in range(i): fibarr+=[Fibonacci(j)]
print("the output for", i ," digits of the Fibonacci array is ", fibarr)
 

the output for 12  digits of the Fibonacci array is  [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


---

The place below is for you - try to *tell* what you did.

You can use graphics, text, links, tables, etc.

---





partial program check (we covered this same program in highschool and i vividly rember it coming in my 10th grade final exam, i wanted to make sure it was the correct code) 

https://www.geeksforgeeks.org/python-program-for-program-for-fibonacci-numbers-2/

after checking the solution was indeed as i recalled, i modified the code to generate the positions in an array and return an array with for loop. code can be optimized more with less lines (the if loops can be really compressed in python to scary extents sometimes) but i wanted to make it more readable at the moment :)


---

What else could you do with Jupyter Notebooks?

Check [here](https://towardsdatascience.com/bringing-the-best-out-of-jupyter-notebooks-for-data-science-f0871519ca29).

**You do not have to put the answers to these questions to your report.**

### Part 3: Google Colab(oratory)

You can run Jupyter Notebooks [locally](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#running-a-notebook-server) and [remotely](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#running-a-public-notebook-server). I especially recommend the security sections here!

Jupyter Notebooks can also be used with cloud solutions, such as AWS, Azure, Google Cloud.

Google Colab operates in such a way.

You can also download the notebook and run it at home using your computer resources. 

A comparison of the different mentioned services is available [here](https://www.dataschool.io/cloud-services-for-jupyter-notebook/). Unfortunately, it is a bit old, and some information is outdated.

You can also use [Docker](https://hub.docker.com/r/jupyter/datascience-notebook/).

By the way, [Azure](https://www.eaiib.agh.edu.pl/azure-elms/) (polish) gives all AGH UST students free $100.

---
One of the main differences (compared to local work): how to upload files to Google Colab?

For example like this:

In [ ]:
from google.colab import files

uploaded = files.upload() # after running the cell, there is a button that allows data upload, which then can be easily accessed

KeyboardInterrupt: ignored

Anyway, you can just use the sidebar on the left and take advantage of the Google Drive integration. More about this issue [here](https://colab.research.google.com/notebooks/io.ipynb).

The sidebar in Google Colab contains search, code snippets, variable preview, and file handling options.

In addition, we also can integrate Colab with GitHub. For more information, please click here: [1](https://medium.com/analytics-vidhya/how-to-use-google-colab-with-github-via-google-drive-68efb23a42d), [2](https://towardsdatascience.com/google-drive-google-colab-github-dont-just-read-do-it-5554d5824228) i [3](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb).

## Middle

⭐ **All the data used in these laboratories are available [here](https://drive.google.com/drive/folders/1xPxoMRhm8KZxODB1tCGK6uzdIpBmTr_u?usp=sharing).** ⭐

You can also download some data directly from scikit-learn, look [here](https://scikit-learn.org/stable/datasets.html).

### Part 4: (Simplified) Exploratory Data Analysis

Sample EDA is available [here](https://colab.research.google.com/drive/1nU3B0AZz3Q5TqF0fATLA45N5HJr04BwJ?usp=sharing). 

There is also a link at the end of the file that explains a lot more.

For the first part, we will use the <ins>swimming dataset</ins>.

Open it using a standard notepad (or better: VS Code, Sublime, etc.). \\
Then use the spreadsheet program (Excel, Google Spreadsheets, LibreOffice Calc, etc.).

Then load the file as shown above into Google Colab.

In [ ]:
from google.colab import files

uploaded = files.upload() # load the file with teh swimming dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import missingno
%matplotlib inline

In [ ]:
df = pd.read_csv('swimming.csv') # displays rows and columns of dataset
print(df.shape)

In [ ]:
df.info() # displays rows and columns of dataset and other info 

In [ ]:
df.dtypes

In [ ]:
def uniq(df):
    columns = df.select_dtypes(include=['object', 'category']).columns
    for i in columns:
        print(" ")
        print("---------------------")
        print("Unique variables of " + i)
        print("---------------------")
        print(df[i].value_counts().reset_index().rename(columns={"index": i, i: "n"})[:min(3, len(df[i].value_counts()))])
        print(" ")
uniq(df)

In [ ]:
swimming = df[df['enjoy'] != 'yes'] # choose only these rows, which represent 'yes' (by enjoy)
swimming.head()

In [ ]:
df['enjoy'].value_counts()

In [ ]:
#ignore this plz test
df = pd.read_csv('swimming.csv')
df.head() 




In [ ]:
swimming = df[df['humidity'] == 'high'] # choose only these rows, which represent 'yes' (by enjoy)
swimming.head()



In [ ]:
df['humidity'].value_counts()

Using [example with iris dataset](https://colab.research.google.com/drive/1nU3B0AZz3Q5TqF0fATLA45N5HJr04BwJ?usp=sharing) answer the following questions. \\
To answer, you need to write a few short lines of code.

1. What is the size (rows, columns) of the dataset?
2. How many variables are there in the dataset? Which of them are the feature variables? What are the others?
3. How many instances are there? How many positive `(enjoy == yes)` and negative instances are in the dataset?
4. Which of the feature variables best separates the data?
5. How many items in the dataset have the humidity variable set to high (`humidity == high`)? What are their numbers in the dataset (counting from 0)?

**Put the answers to these questions and the code in your report.** \\
**You can get 1 point for each correct answer.**

In [ ]:
# check the data

In [ ]:
# TESTING ONLY CODE CREDIT TO https://www.analyticsvidhya.com/blog/2021/05/exploratory-data-analysis-eda-a-step-by-step-guide/
#  https://gist.github.com/jiahao87/c97214065f996b76ab8fe4ca1964b2b5



import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import missingno
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
     
def numeric_eda(df, hue=None):
    """Given dataframe, generate EDA of numeric data"""
    print("\nTo check: \nDistribution of numeric data")
    display(df.describe().T)
    columns = df.select_dtypes(include=np.number).columns
    figure = plt.figure(figsize=(20, 10))
    figure.add_subplot(1, len(columns), 1)
    for index, col in enumerate(columns):
        if index > 0:
            figure.add_subplot(1, len(columns), index + 1)
        sns.boxplot(y=col, data=df, boxprops={'facecolor': 'None'})
    figure.tight_layout()
    plt.show()
    
    if len(df.select_dtypes(include='category').columns) > 0:
        for col_num in df.select_dtypes(include=np.number).columns:
            for col in df.select_dtypes(include='category').columns:
                fig = sns.catplot(x=col, y=col_num, kind='violin', data=df, height=5, aspect=2)
                fig.set_xticklabels(rotation=90)
                plt.show()
    
    # Plot the pairwise joint distributions
    print("\nTo check pairwise joint distribution of numeric data")
    if hue==None:
        sns.pairplot(df.select_dtypes(include=np.number))
    else:
        sns.pairplot(df.select_dtypes(include=np.number).join(df[[hue]]), hue=hue)
    plt.show()


def top5(df):
    """Given dataframe, generate top 5 unique values for non-numeric data"""
    columns = df.select_dtypes(include=['object', 'category']).columns
    for col in columns:
        print("Top 5 unique values of " + col)
        print(df[col].value_counts().reset_index().rename(columns={"index": col, col: "Count"})[
              :min(5, len(df[col].value_counts()))])
        print(" ")
    
    
def categorical_eda(df, hue=None):
    """Given dataframe, generate EDA of categorical data"""
    print("\nTo check: \nUnique count of non-numeric data\n")
    print(df.select_dtypes(include=['object', 'category']).nunique())
    top5(df)
    # Plot count distribution of categorical data
    for col in df.select_dtypes(include='category').columns:
        fig = sns.catplot(x=col, kind="count", data=df, hue=hue)
        fig.set_xticklabels(rotation=90)
        plt.show()
    

def eda(df):
    """Given dataframe, generate exploratory data analysis"""
    # check that input is pandas dataframe
    if type(df) != pd.core.frame.DataFrame:
        raise TypeError("Only pandas dataframe is allowed as input")
        
    # replace field that's entirely space (or empty) with NaN
    df = df.replace(r'^\s*$', np.nan, regex=True)

    print("Preview of data:")
    display(df.head(3))

    print("\nTo check: \n (1) Total number of entries \n (2) Column types \n (3) Any null values\n")
    print(df.info())

    # generate preview of entries with null values
    if df.isnull().any(axis=None):
        print("\nPreview of data with null values:")
        display(df[df.isnull().any(axis=1)].head(3))
        missingno.matrix(df)
        plt.show()

    # generate count statistics of duplicate entries
    if len(df[df.duplicated()]) > 0:
        print("\n***Number of duplicated entries: ", len(df[df.duplicated()]))
        display(df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head())
    else:
        print("\nNo duplicated entries found")

    # EDA of categorical data
    categorical_eda(df)
    
    # EDA of numeric data
    numeric_eda(df)
        
    # Plot time series plot of numeric data
    time_series_plot(df)

---

**Extra task (not obligatory).**

Perform full EDA.

In [ ]:
# set categorical data
df['sky'] = df['sky'].astype('category')
df['airTemp'] = df['airTemp'].astype('category')
df['humidity'] = df['humidity'].astype('category')
df['wind'] = df['wind'].astype('category')
df['water'] = df['water'].astype('category')
df['forecast'] = df['forecast'].astype('category')
df['enjoy'] = df['enjoy'].astype('category')

In [ ]:
eda(df)

In [ ]:
sns.countplot(df['enjoy'])

In [ ]:
sns.countplot(df['forecast'])


In [ ]:
sns.countplot(df['water'])


In [ ]:
sns.countplot(df['wind'])


In [ ]:
sns.countplot(df['humidity'])


In [ ]:
sns.countplot(df['airTemp'])


In [ ]:
sns.countplot(df['sky'])

In [ ]:
sns.countplot(df['enjoy'],hue=df['forecast'])

In [ ]:
sns.countplot(df['enjoy'],hue=df['water'])

In [ ]:
sns.countplot(df['enjoy'],hue=df['wind'])

In [ ]:
sns.countplot(df['enjoy'],hue=df['humidity'])

In [ ]:
sns.countplot(df['enjoy'],hue=df['airTemp'])

In [ ]:
sns.countplot(df['enjoy'],hue=df['sky'])

### Part 5: Linear Regression


Learn more about regression here: [1](https://towardsdatascience.com/a-brief-introduction-to-supervised-learning-54a3e3932590), [2](https://realpython.com/linear-regression-in-python/), [3](https://towardsdatascience.com/simple-and-multiple-linear-regression-in-python-c928425168f9).

Based on the descriptions in the links,  solve further tasks.

Load <ins>cpu</ins> i <ins>spu-vendor</ins> datasets.
Use `pandas` and `read_csv()`. 

Attention! To solve exercises, use [to_numpy()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy) or [values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html).

For these of you who are interested -- data are selected from: <br>
Kilpatrick, D. A., & Cameron-Jones, R. M. (1998). Numeric prediction using instance-based learning with encoding length selection. <br> 
In: *1997 International Conference on Neural Information Processing and Intelligent Information Systems* (Vol. 1, pp. 984-987).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import missingno
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [ ]:
from google.colab import files

uploaded = files.upload() # load the file with teh swimming dataset

Saving cpu.csv to cpu.csv


In [ ]:
from google.colab import files

uploaded = files.upload() # load the file with teh swimming dataset

Saving cpu_vendor.csv to cpu_vendor.csv


In [ ]:
df1 = pd.read_csv('cpu.csv') # displays rows and columns of dataset
print(df1.shape)

(209, 7)


In [ ]:
df2 = pd.read_csv('cpu_vendor.csv') # displays rows and columns of dataset
print(df2.shape)

(209, 8)


In [ ]:
 df1.to_numpy()

array([[  125,   256,  6000, ...,    16,   128,   198],
       [   29,  8000, 32000, ...,     8,    32,   269],
       [   29,  8000, 32000, ...,     8,    32,   220],
       ...,
       [  125,  2000,  8000, ...,     2,    14,    52],
       [  480,   512,  8000, ...,     0,     0,    67],
       [  480,  1000,  4000, ...,     0,     0,    45]])

In [ ]:
 df2.to_numpy()

array([['adviser', 125, 256, ..., 16, 128, 199],
       ['amdahl', 29, 8000, ..., 8, 32, 253],
       ['amdahl', 29, 8000, ..., 8, 32, 253],
       ...,
       ['sratus', 125, 2000, ..., 2, 14, 41],
       ['wang', 480, 512, ..., 0, 0, 47],
       ['wang', 480, 1000, ..., 0, 0, 25]], dtype=object)

In [ ]:
# load dane

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   MYCT    209 non-null    int64
 1   MMIN    209 non-null    int64
 2   MMAX    209 non-null    int64
 3   CACH    209 non-null    int64
 4   CHMIN   209 non-null    int64
 5   CHMAX   209 non-null    int64
 6   class   209 non-null    int64
dtypes: int64(7)
memory usage: 11.6 KB


In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   vendor  209 non-null    object
 1   MYCT    209 non-null    int64 
 2   MMIN    209 non-null    int64 
 3   MMAX    209 non-null    int64 
 4   CACH    209 non-null    int64 
 5   CHMIN   209 non-null    int64 
 6   CHMAX   209 non-null    int64 
 7   class   209 non-null    int64 
dtypes: int64(7), object(1)
memory usage: 13.2+ KB


In [ ]:
df1.dtypes

MYCT     int64
MMIN     int64
MMAX     int64
CACH     int64
CHMIN    int64
CHMAX    int64
class    int64
dtype: object

In [ ]:
df2.dtypes

vendor    object
MYCT       int64
MMIN       int64
MMAX       int64
CACH       int64
CHMIN      int64
CHMAX      int64
class      int64
dtype: object

In [ ]:
np.shape('vendor')

()

In [ ]:
df2 = pd.read_csv('cpu_vendor.csv') # displays rows and columns of dataset
print(df2)

      vendor  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  class
0    adviser   125   256   6000   256     16    128    199
1     amdahl    29  8000  32000    32      8     32    253
2     amdahl    29  8000  32000    32      8     32    253
3     amdahl    29  8000  32000    32      8     32    253
4     amdahl    29  8000  16000    32      8     16    132
..       ...   ...   ...    ...   ...    ...    ...    ...
204   sperry   124  1000   8000     0      1      8     37
205   sperry    98  1000   8000    32      2      8     50
206   sratus   125  2000   8000     0      2     14     41
207     wang   480   512   8000    32      0      0     47
208     wang   480  1000   4000     0      0      0     25

[209 rows x 8 columns]


In [ ]:
# df = pd.read_csv('cpu_vendor.csv') # displays rows and columns of dataset
#df['vendor'] = pd.get_dummies(df['vendor'])

df2 = pd.read_csv('cpu_vendor.csv') # displays rows and columns of dataset

df2 = pd.concat([pd.get_dummies(df2['vendor']), df2.drop('vendor', axis=1)], axis=1)

print(df2)

     adviser  amdahl  apollo  basf  bti  burroughs  c.r.d  cambex  cdc  dec  \
0          1       0       0     0    0          0      0       0    0    0   
1          0       1       0     0    0          0      0       0    0    0   
2          0       1       0     0    0          0      0       0    0    0   
3          0       1       0     0    0          0      0       0    0    0   
4          0       1       0     0    0          0      0       0    0    0   
..       ...     ...     ...   ...  ...        ...    ...     ...  ...  ...   
204        0       0       0     0    0          0      0       0    0    0   
205        0       0       0     0    0          0      0       0    0    0   
206        0       0       0     0    0          0      0       0    0    0   
207        0       0       0     0    0          0      0       0    0    0   
208        0       0       0     0    0          0      0       0    0    0   

     ...  sperry  sratus  wang  MYCT  MMIN   MMAX  

In [ ]:

#Use LinearRegression for both datasets: model = LinearRegression(), model.fit(), model.score() with right parameters. 
#You can use different parameters and check the results. Your task is to predict class. 
#What are the differences in the scores of the models? What is the mathematical complexity of the models?


from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


dataset = pd.read_csv('cpu_vendor.csv') 

dataset = pd.concat([pd.get_dummies(dataset['vendor']), dataset.drop('vendor', axis=1)], axis=1) #get dummies remove key error

 #assign x and y

In [ ]:
x=  dataset.iloc[:, :-1].values  # all but class
print (x)

[[  1   0   0 ... 256  16 128]
 [  0   1   0 ...  32   8  32]
 [  0   1   0 ...  32   8  32]
 ...
 [  0   0   0 ...   0   2  14]
 [  0   0   0 ...  32   0   0]
 [  0   0   0 ...   0   0   0]]


In [ ]:
print ("Dataset.head() \n ", dataset.head())


Dataset.head() 
     adviser  amdahl  apollo  basf  bti  burroughs  c.r.d  cambex  cdc  dec  \
0        1       0       0     0    0          0      0       0    0    0   
1        0       1       0     0    0          0      0       0    0    0   
2        0       1       0     0    0          0      0       0    0    0   
3        0       1       0     0    0          0      0       0    0    0   
4        0       1       0     0    0          0      0       0    0    0   

   ...  sperry  sratus  wang  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  class  
0  ...       0       0     0   125   256   6000   256     16    128    199  
1  ...       0       0     0    29  8000  32000    32      8     32    253  
2  ...       0       0     0    29  8000  32000    32      8     32    253  
3  ...       0       0     0    29  8000  32000    32      8     32    253  
4  ...       0       0     0    29  8000  16000    32      8     16    132  

[5 rows x 37 columns]


In [ ]:
print("\nFirst 10 Input Values : \n", x[0:10, :])


First 10 Input Values : 
 [[    1     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0   125   256  6000   256    16   128]
 [    0     1     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0    29  8000 32000    32     8    32]
 [    0     1     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0    29  8000 32000    32     8    32]
 [    0     1     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0    29  8000 32000    32     8    32]
 [    0     1     0     0     0     0     0     0     0     0     0     0
      0

In [ ]:

y = dataset['class'].values 
print (y)
y1 = y
y1 = y1.reshape(-1, 1)
print("\n\nFirst 10 Output true value : \n", y1[0:10, :])

[ 199  253  253  253  132  290  381  381  749 1238   23   24   70  117
   15   64   23   29   22  124   35   39   40   45   28   21   28   22
   28   27  102  102   74   74  138  136   23   29   44   30   41   74
   74   74   54   41   18   28   36   38   34   19   72   36   30   56
   42   34   34   34   34   34   19   75  113  157   18   20   28   33
   47   54   20   23   25   52   27   50   18   53   23   30   73   20
   25   28   29   32  175   57  181  181   32   82  171  361  350  220
  113   15   21   35   18   20   20   28   45   18   17   26   28   28
   31   31   42   76   76   26   59   65  101  116   18   20   20   30
   44   44   82   82  128   37   46   46   80   88   88   33   46   29
   53   53   41   86   95  107  117  119  120   48  126  266  270  426
  151  267  603   19   21   26   35   41   47   62   78   80   80  142
  281  190   21   25   67   24   24   64   25   20   29   43   53   19
   22   31   41   47   99   67   81  149  183  275  382   56  182  227
  341 

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 0)

model = LinearRegression()

model.fit(xtrain, ytrain) #fit

r_sq = model.score(xtest, ytest)

In [ ]:
y_pred = model.predict(xtest)
print(f"predicted response x:\n{y_pred}")
   
y_pred1 = y_pred
y_pred1 = y_pred1.reshape(-1,1)
   
print("\n   RESULT OF LINEAR REGRESSION PREDICTION : ")
print ("\nFirst 10 Predicted value : \n", y_pred1[0:10, :])

predicted response x:
[ 34.96219718 -63.62905215  85.10288078 329.79562195  99.05069405
 -70.83748694  78.43773879  48.56398268 216.35643742 157.4287584
  35.49906714 539.38780353  82.80865695 246.45641894 472.57975677
 -48.97262973  72.4732777   -7.13119156 -26.07826145 -60.31571147
  -8.09163848 147.49434049 467.78284969  56.74806962 -15.50528646
 110.55364292 -12.88444902   3.87250729 -34.282316    49.41124133
  64.5477403   -2.64524057   1.40177849 141.05971152 144.78549101
  69.08448032  -3.54689037  37.10263258 -63.20761797 110.89945375
 263.63796024  77.0052194 ]

   RESULT OF LINEAR REGRESSION PREDICTION : 

First 10 Predicted value : 
 [[ 34.96219718]
 [-63.62905215]
 [ 85.10288078]
 [329.79562195]
 [ 99.05069405]
 [-70.83748694]
 [ 78.43773879]
 [ 48.56398268]
 [216.35643742]
 [157.4287584 ]]


In [ ]:
dataset.keys()

Index(['adviser', 'amdahl', 'apollo', 'basf', 'bti', 'burroughs', 'c.r.d',
       'cambex', 'cdc', 'dec', 'dg', 'formation', 'four-phase', 'gould',
       'harris', 'honeywell', 'hp', 'ibm', 'ipl', 'magnuson', 'microdata',
       'nas', 'ncr', 'nixdorf', 'perkin-elmer', 'prime', 'siemens', 'sperry',
       'sratus', 'wang', 'MYCT', 'MMIN', 'MMAX', 'CACH', 'CHMIN', 'CHMAX',
       'class'],
      dtype='object')

1. What all these variables mean? Check [here](https://archive.ics.uci.edu/ml/datasets/Computer+Hardware). Attention! `class` $\equiv$ `PRP`.
2. How do these datasets differ?
3. What type is the `vendor` and `class` data series? Use `dtype`.
4. String cannot be used in linear regression. But `vendor` describes categories and this is fine for us. <br> Use `df['vendor'] = pd.get_dummies(df['vendor'])`. What happened?
5. Use LinearRegression for both datasets: `model = LinearRegression(), model.fit(), model.score()` with right parameters. You can use different parameters and check the results. Your task is to predict `class`. 
What are the differences in the scores of the models? What is the mathematical complexity of the models?
6. What are the coefficients of the regression equation? Check them using `model.coef_` i `model.intercept_`. What do they mean?
7. What will be the value of `class` depending on the data the user enters? Try to predict the results for a few examples. How to do it? <br> [Look here](https://gist.github.com/a-i-dan/413f779292788cb3a7106a5a7efde938/) or just use `model.predict()`.

Hint to 4:
`df = pd.concat([pd.get_dummies(df['vendor']), df.drop('vendor', axis=1)], axis=1)` <br> allows for creating dataframe that is OK for the model. Why?

**Put the answers to these questions (1 and 7 is not obligatory).** \\
**You can get 1 point for each correct answer.**

In [ ]:
# check the data and perform regression task

In [ ]:
# predict



print(f"coefficient of determination: {r_sq}")

print(f"intercept: {model.intercept_}")

print(f"slope: {model.coef_}")


coefficient of determination: 0.7791673058680394
intercept: -76.7635817080922
slope: [-1.21924344e+02 -5.64759266e+00  3.24504704e+01 -2.42820193e+01
  5.95723139e+01 -4.40969929e+01  3.80707825e+01  2.63681516e+01
  1.28558635e+01  1.78652928e+01  2.96932061e+01 -1.08355439e+00
  5.01427746e+01 -4.28363744e+01  2.56831882e+00 -4.98145223e+01
  2.10604755e+01 -2.60765921e+00 -5.56711050e+00  2.62345539e+01
 -1.59187495e+02 -2.52654945e+01 -3.21334833e+00  2.22531103e+01
  2.91592274e+01  2.13129601e+01  2.02428200e+01  5.01648142e+01
  3.64988643e+00  2.18614851e+01  7.17060313e-02  1.93664453e-02
  5.50274655e-03  5.51605598e-01 -2.09115212e+00  1.89842018e+00]


### Part 6: Decision Trees

Learn about decision trees here: [1](https://towardsdatascience.com/how-to-do-decision-trees-in-python-and-r-2b0902b097ec), [2](https://towardsdatascience.com/the-complete-guide-to-decision-trees-28a4e3c7be14), [3](https://dinhanhthi.com/decision-tree-classifier).

Introductory questions:

1. What is the main difference between ID3 and CART?
2. What is `gini` and `entropy`? 

**You do not have to put anything in your report, just think.**

Use <ins>swimming dataset</ins> and answer following questions.

1. Try to draw a decision tree for this data set on a piece of paper. We predict whether the given conditions will be liked -- `enjoy`.
2. Fill in the code below and check if the figure corresponds to the one you drew.
3. What are `gini` and `entropy` values? What do they mean?
4. Are the generated trees different depending on parameters?
5. Reduce the number of variable features -- e.g. remove airTemp -- how do it influence the results?

**Put the code into your report.** \\
**You can get 2 points for full (see below) correct solution.**

In [ ]:
# load the data

In [ ]:
from sklearn import tree

clf_entropy = # fill
clf_gini = # fill

In [ ]:
# present the data

sky airTemp humidity    wind water forecast enjoy
0   sunny    warm   normal  strong  warm     same   yes
1   sunny    warm     high  strong  warm     same   yes
2   rainy    cold     high  strong  warm   change    no
3   sunny    warm     high  strong  cool   change   yes
4  cloudy    warm   normal    weak  warm     same   yes

In [ ]:
x = pd.get_dummies(df.drop('enjoy', axis=1))
y = # fill

clf = # fill

In [ ]:
pd.get_dummies(df.drop('enjoy', axis=1)) # what is going on here?

sky_cloudy  sky_rainy  sky_sunny  ...  water_warm  forecast_change  forecast_same
0           0          0          1  ...           1                0              1
1           0          0          1  ...           1                0              1
2           0          1          0  ...           1                1              0
3           0          0          1  ...           0                1              0
4           1          0          0  ...           1                0              1
5           1          0          0  ...           0                0              1

[6 rows x 13 columns]

In [ ]:
# use the following code to visualize the tree

from IPython.display import Image
import pydotplus

columns = pd.get_dummies(df.drop('enjoy', axis=1)).columns

dot_data = tree.export_graphviz(clf, out_file=None, rounded=True, filled=True, feature_names=columns)
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())

1. What the next lines in the 'cells' of the tree mean? 'X <= R', 'gini/entropy = Y', 'samples = Z', 'value = V'?
2. Use `model.predict()`, to predict `enjoy` for several instances from dataset and propose your own examples.

**Put the code into your report.** \\
**You can get 2 points for (full) correct solution.**

In [ ]:
# predict

Using the example above, generate the decision tree for <ins>iris</ins> dataset. We predict the iris name!

1. Do we need to use `pd.get_dummies()`? Why or why not?
2. What do the `max_depth`, `min_samples_split`, `min_samples_leaf` parameters do?
3. Generate graphical representations of the decision trees for different values of parameters above.

**Put the answers to these questions.** \\
**You can get 1 point for each correct answer.**

In [ ]:
# model

1. Use `model.predict()`, to predict iris name for several instances from dataset and propose your own examples.
2. Can we use decision trees for regression task? 

**You do not have to put the answers to these questions in your report.**

In [ ]:
# predict

**Extra task (not obligatory).**

Spróbuj wykorzystać SVM, kNN, NB i RF analogicznie jak drzewa decyzyjne.

In [ ]:
# SVM

In [ ]:
# kNN

In [ ]:
# NB

In [ ]:
# RF - what are ensemble methods?

### Part 7: Neural Networks

Learn about neural networks here: [1](https://towardsdatascience.com/machine-learning-for-beginners-an-introduction-to-neural-networks-d49f22d238f9), [2](https://towardsdatascience.com/first-neural-network-for-beginners-explained-with-code-4cfd37e06eaf), [3](https://www.kdnuggets.com/2016/10/beginners-guide-neural-networks-python-scikit-learn.html).

1. Draw 3 neurons (sheet of paper, notepad, whatever). Neurons have:
  *   Two binary inputs: x<sub>1</sub>, x<sub>2</sub>
  *   Additional input - constant - what is its other name?
  *   **Weights - determine them!**
  *   Activation function f(x) where $f(x)=1$ for $\sum w_i*x_i \geq 0$ or $f(x)=0$ dla $\sum w_i*x_i < 0$.
  *   To represent following these operations: $x_1 OR \ x_2$, $x_1 AND \ x_2$, $x_1 XOR \ x_2$. Czy jest to możliwe? [Hint](https://medium.com/@stanleydukor/neural-representation-of-and-or-not-xor-and-xnor-logic-gates-perceptron-algorithm-b0275375fea1).
2. Using [this tool](https://playground.tensorflow.org), try to understand how neural networks work.
  * Try different combinations of input parameters (features), activation functions, etc.
  * Do not use hidden layers. For which set was the training unsuccessful? Why?
  * Use hidden layers. How many layers are enough for the network to work for each example?
  * What patterns do hidden neurons learn? You can hover the mouse over them to check it.
  * Try adding some noise. It resembles reality more now!
  * Challenge: try to train the spiral dataset with as few neurons, layers and epochs as possible!

3. Complete the code starting with loading the file <ins>diabetes</ins>. More information is available on [Kaggle](https://www.kaggle.com/uciml/pima-indians-diabetes-database).
4. What do the variables mean?
5. What do we predict?
6. What are the dimensions of X? How many features do we have?
7. Is it classification or regression?

Dataset from:
Smith, J. W., Everhart, J. E., Dickson, W. C., Knowler, W. C., & Johannes, R. S. (1988, November). Using the ADAP learning algorithm to forecast the onset of diabetes mellitus. In: *Proceedings of the Annual Symposium on Computer Application in Medical Care* (p. 261). American Medical Informatics Association.

**Attention! You do not have to answer all these questions but your report contains some additional ones.** \\
**You can get 1 point for each correct answer.**

In [ ]:
# load the file

In [ ]:
df = pd.read_csv('diabetes.csv')
df.head()

In [ ]:
# check type of columns in df

In [ ]:
# count the number of instances, calculate means, variances, etc.

In [ ]:
# show how many classes are there

In [ ]:
x = df.drop('class', axis=1).values
y = df['class'].to_numpy()

In [ ]:
# check type of x and y

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0) # what is going on here?

In [ ]:
### NEURAL NETWORK TRAINING ###

# you do not have to change anything here (for now), just run it

from keras.models import Sequential
from keras.layers import Dense

NB_EPOCHS = 1000 
BATCH_SIZE = 16

model = Sequential()

# adding layers
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid' ))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) # metrics

print('Starting training...')

history = model.fit(X_train,
                    y_train,
                    validation_data=(X_test, y_test),
                    epochs=NB_EPOCHS,
                    batch_size=BATCH_SIZE,
                    verbose=1)

In [ ]:
# visualisation

1. Use this [link](https://www.tensorflow.org/api_docs/python/tf/keras/utils/plot_model) to visualise architecture of this network.
2. How many layers are there?
3. What is a batch size? 
4. What are epochs? Look [here](https://stats.stackexchange.com/questions/153531/what-is-batch-size-in-neural-network).

**Put answers to last to questions to your report.** \\
**You can get 1 point for correct answer.**

1. Using `model.predict()` i `model.predict_classes()` try to predict classes for several instances from provided dataset and your own examples.
2. What is the difference between these two functions?

**You do not have to put your answer into report to these questions.** \\

In [ ]:
# predict

### Part 8: Validation

Following previous example

In [ ]:
# run this code

import matplotlib.pyplot as plt
%matplotlib inline

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'])
plt.show()

Is this `overfitting`, `underfitting` or is it just ok? Analyze similar [example](https://aigeekprogrammer.com/convnets-and-overfitting/).

**Put the answer to this question to your report.** \\
**You can get 2 points for correct answer.**

Check the code marked as `### NEURAL NETWORK TRAINING ###` and choose other [metrics](https://keras.io/api/metrics/classification_metrics/).

**Put the answer to this question to your report.** \\
**You can get 2 points for correct answer.**

In [ ]:
# changed code

Try to visualize them as above.

In [ ]:
# visualise

## End

### Part 9: Share

Share links to sources (articles, books, studies, etc.) that allowed you to answer questions from these labs.

You can also upload other interesting AI and/or supervised learning materials.

**Put the sources into your report.**

### Part 10: Feedback

1. What was missing?
2. Is there anything that you believe should be covered more thoroughly?
3. Did you get interested in the topic?
4. Would you like to know more?
5. Was it worth it?

**Put the feedback into your report.**

## Thank you!

Thank you for participation and you active presence!